Repository captableinc/captable, pull requests merged in 2024-07, with the labels that each got.

#435 feat: add rbac for apikeys
  prisma/migrations/20240711071304_add_missing_field_for_api_key/migration.sql
  prisma/schema.prisma
  src/app/(authenticated)/(dashboard)/[publicId]/settings/api/components/table.tsx
  src/app/(authenticated)/(dashboard)/[publicId]/settings/api/page.tsx
  src/components/common/empty-state.tsx
  src/components/ui/un-authorized-state.tsx
  src/lib/crypto.ts
  src/lib/rbac/subjects.ts
  src/server/api/auth.ts
  src/trpc/routers/api-key/router.ts
Labels: ❓QUESTION

#436 feat: Create Investor Modal
  src/components/modals/index.ts
  src/components/modals/investor/add-investor-form.tsx
  src/components/modals/investor/add-investor-modal.tsx
  src/components/modals/stakeholder/single-stake-holder-form.tsx
  src/lib/utils.ts
Labels: PR: needs change

#437 feat: add rbac for company
  src/app/(authenticated)/(dashboard)/[publicId]/settings/company/page.tsx
  src/lib/rbac/subjects.ts
  src/trpc/routers/company-router/router.ts
Labels: PR: needs change

#407 feat: openapi for stakeholder endpoint
  postman/collection.json
  src/server/api/auth.ts
  src/server/api/hono.ts
  src/server/api/index.ts
  src/server/api/pagination/find-many.proxy.ts
  src/server/api/pagination/prisma-proxy.ts
  src/server/api/pagination/types.ts
  src/server/api/routes/company/getMany.ts
  src/server/api/routes/company/getOne.ts
  src/server/api/routes/company/stakeholder/create.ts
  src/server/api/routes/company/stakeholder/delete.ts
  src/server/api/routes/company/stakeholder/getMany.ts
  src/server/api/routes/company/stakeholder/getOne.ts
  src/server/api/routes/company/stakeholder/index.ts
  src/server/api/routes/company/stakeholder/update.ts
  src/server/api/schema/pagination.ts
  src/server/api/schema/stakeholder.ts
  src/server/api/utils.ts
  src/server/services/stakeholder/add-stakeholders.ts
  src/server/services/stakeholder/delete-stakeholder.ts
  src/server/services/stakeholder/get-stakeholder-by-id.ts
  src/server/services/stakeholder/get-stakeholders.ts
  src/server/services/stakeholder/update-stakeholder.ts
  src/trpc/routers/safe/procedures/create-safe.ts
  src/trpc/routers/stakeholder-router/procedures/get-stakeholders.ts
  src/trpc/routers/stakeholder-router/schema.ts
Labels: PR: needs review

#458 fix: separated vestingSchedule
  prisma/migrations/20240723005834_separate_vesting_schedule/migration.sql
  prisma/schema.prisma
  src/components/securities/options/steps/vesting-details.tsx
  src/components/securities/shares/steps/general-details.tsx
  src/components/update/editor.tsx
  src/server/api/routes/company/share/create.ts
  src/server/api/schema/shares.ts
  src/server/services/shares/add-share.ts
  src/trpc/routers/securities-router/procedures/add-option.ts
  src/trpc/routers/securities-router/procedures/add-share.ts
  src/trpc/routers/securities-router/procedures/get-options.ts
  src/trpc/routers/securities-router/procedures/get-shares.ts
  src/trpc/routers/securities-router/schema.ts
Labels: PR: needs change

#450 feat: add sign template status
  prisma/migrations/20240718054727_add_more_status_in_template_status/migration.sql
  prisma/schema.prisma
  src/app/(authenticated)/(dashboard)/[publicId]/documents/esign/components/table.tsx
  src/app/(authenticated)/(dashboard)/[publicId]/documents/esign/components/temp-cancel-btx.tsx
  src/app/(authenticated)/(dashboard)/[publicId]/documents/esign/v/[templatePublicId]/page.tsx
  src/app/(documents)/esign/[token]/page.tsx
  src/jobs/esign-email.ts
  src/trpc/routers/template-router/procedures/cancel-template.ts
  src/trpc/routers/template-router/procedures/get-signing-fields.tsx
  src/trpc/routers/template-router/procedures/sign-template.ts
  src/trpc/routers/template-router/router.ts
  src/trpc/routers/template-router/schema.ts
Labels: PR: needs review
